# Get VirtualBox to Vagrant package with `vagrant package --base "<VirtualBoxName>"`
# Add box via `vagrant box add /path/to/created/package.box --name dsn`
# Multi-Machine Help: https://www.vagrantup.com/docs/multi-machine/index.html

Vagrant.configure("2") do |config|  

    config.vm.box = "dsn"
    #config.vm.synced_folder "to_vm/", "/etc/to_vm/"
  
    config.ssh.username = "root"
    config.ssh.insert_key = true
    config.ssh.private_key_path = "keys/dsnkey"
  
    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 1
        vb.memory = 1024
      end

    # TODO Config Network so that they can connect to each other!
    config.vm.define "dsn1" do |dsn1|
        dsn1.vm.provider "virtualbox" do |vb|
            vb.name = "Vagrant-Docker Swarm Node 1"
          end
    end

    config.vm.define "dsn2" do |dsn2|
        dsn2.vm.provider "virtualbox" do |vb|
            vb.name = "Docker Swarm Node 2"
        end
    end

    # TODO Linked Clones lookup that can be very useful
    #config.vm.provider "virtualbox" do |v|
    #  v.linked_clone = true
    #end
    

  end