version: "3.3"

networks:
    pgnet:
        driver: overlay
        attachable: true

configs:
    tables:
        external: true

    sub_config:
        external: true

    sub_setup:
        external: true

volumes:
    pgdata:
        external: true

services:

    db:
        hostname: 'subscriber10'
        image: mypglog:10-raw
        environment:
            - POSTGRES_PASSWORD=pass
            - POSTGRES_USER=postgres
            - POSTGRES_DB=testdb
            - PGDATA=/var/lib/postgresql/10/data #Already set in Image, here just again to make it clear and reader friendly.
            - PROVIDER_IP=192.168.99.149 # TODO how to make this dynamic by somehow getting this value from ../.env.sh?
        volumes: 
            - /etc/sub_setup.sh:/etc/sub_setup.sh
            #- pgdata:/var/lib/postgresql/10/data # BIG TODO!!: Due to volume usage, restarted container will be in the role whatever the container before had!! Maybe clear volume at every container start?
        configs:
            - source: tables
              target: /docker-entrypoint-initdb.d/init.sql
            - source: sub_config
              target: /usr/share/postgresql/postgresql.conf.sample
        ports:
            - target: 5432
              published: 5432
              protocol: tcp
              mode: host
        networks:
            - pgnet
        deploy:
            placement:
              constraints:
                - "node.labels.pg_ver==10"
            mode: replicated
            replicas: 0