version: "3.3"

networks:
    pgnet:
        driver: overlay
        attachable: true

configs:
    bench:
        external: true

    tables:
        external: true

    sub_config:
        external: true

    sub_setup:
        external: true

volumes:
    pgdata:
        external: true

services:

    adminer:
        image: adminer:4.7.2 
        environment:
          - ADMINER_DEFAULT_SERVER=192.168.99.149
        networks:
          - pgnet
        ports:
          - 8082:8080
        deploy:
          mode: replicated
          replicas: 1

    db:
        hostname: 'subscriber95'
        image: mypglog:9.5-raw
        environment:
            - POSTGRES_PASSWORD=pass
            - POSTGRES_USER=postgres
            - POSTGRES_DB=testdb
            - PGDATA=/var/lib/postgresql/9.5/data #Already set in Image, here just again to make it clear and reader friendly.
        volumes: 
            - /etc/upgrade_to_v10.sh:/etc/upgrade_to_v10.sh 
            #- pgdata:/var/lib/postgresql/9.5/data # BIG TODO!!: Due to volume usage, restarted container will be in the role whatever the container before had!! Maybe clear volume at every container start?
        configs:
            - source: bench
              target: /custom_benchmark.sql
            - source: tables
              target: /docker-entrypoint-initdb.d/init.sql
            - source: sub_config
              target: /usr/share/postgresql/postgresql.conf.sample
            - source: sub_setup
              target: /docker-entrypoint-initdb.d/sub_setup.sh
        ports:
            - target: 5432
              published: 5433
              protocol: tcp
              mode: host
            - "5432:5432"
        networks:
            - pgnet
        deploy:
            mode: replicated
            replicas: 1