version: "3.3"

networks:
    pgnet:

volumes:
    pgdata95:

services:

    #adminer:
    #    image: adminer:4.7.2 
    #    environment:
    #      - ADMINER_DEFAULT_SERVER=192.168.99.149
    #    networks:
    #      - pgnet
    #    ports:
    #      - 8082:8080

    db95:
        hostname: 'subscriber95'
        image: mypglog:9.5
        environment:
            - POSTGRES_PASSWORD=pass # Always set, needed for sub_setups.sh
            - POSTGRES_USER=postgres # Always set, needed for sub_setups.sh
            - POSTGRES_DB=testdb # Always set, needed for sub_setups.sh TODO how to make this dynamic by somehow getting this value from ../.env.sh?
            - PGDATA=/var/lib/postgresql/9.5/data  # Always set, needed for docker_entrypoint.sh
            - PROVIDER_IP=192.168.99.149 # TODO how to make this dynamic by somehow getting this value from ../.env.sh?
        volumes: 
            - pgdata95:/var/lib/postgresql/9.5/data
            - ../postgres/sub_setup.sh:/etc/sub_setup.sh
            - ../postgres/table_setup.sql:/docker-entrypoint-initdb.d/init.sql
            - ../postgres/sub_postgresql.conf:/usr/share/postgresql/postgresql.conf.sample
        ports:
            - target: 5432
              published: 5432
              protocol: tcp
              mode: host
        networks:
            - pgnet