version: "3.3"

networks:
    pgnet:

volumes:
    pgdata10:
    pgdata95:

services:

    db10:
        hostname: 'subscriber10'
        image: mypglog:10
        environment:
            - POSTGRES_PASSWORD=pass # Always set, needed for sub_setups.sh
            - POSTGRES_USER=postgres # Always set, needed for sub_setups.sh
            - POSTGRES_DB=testdb # Always set, needed for sub_setups.sh
            - PGDATA_OLD=/var/lib/postgresql/9.5/data
            - PGDATA=/var/lib/postgresql/10/data  # Always set, needed for docker_entrypoint.sh
            - PROVIDER_IP=192.168.99.149 # TODO how to make this dynamic by somehow getting this value from ../.env.sh?
        volumes: 
            - pgdata95:/var/lib/postgresql/9.5/data
            - pgdata10:/var/lib/postgresql/10/data
            - ../postgres/sub_setup.sh:/etc/sub_setup.sh
            #- pgdata:/var/lib/postgresql/10/data # BIG TODO!!: Due to volume usage, restarted container will be in the role whatever the container before had!! Maybe clear volume at every container start?
            - ../postgres/table_setup.sql:/docker-entrypoint-initdb.d/init.sql
            - ../postgres/sub_postgresql.conf:/usr/share/postgresql/postgresql.conf.sample
        ports:
            - target: 5432
              published: 5432
              protocol: tcp
              mode: host
        networks:
            - pgnet