version: "3.3"

networks:
    pgnet:

configs:
    tables:
        external: true

    prov_config:
        external: true

    prov_setup:
        external: true

    sub_config:
        external: true

    sub_setup:
        external: true

services:

    adminer:
        image: adminer:4.7.2 
        environment:
            - ADMINER_DEFAULT_SERVER=primary
        networks:
            - pgnet
        ports:
            - 8082:8080

    provider:
        hostname: 'provider95'
        image: mypglog:9.5-raw
        #command: 'postgres -c config_file=/etc/postgresql/postgresql.conf'
        environment:
            - POSTGRES_PASSWORD=pass
            - POSTGRES_USER=primaryuser
            - POSTGRES_DB=testdb
        configs:
            - source: tables
              target: /docker-entrypoint-initdb.d/init.sql
            - source: prov_config
              target: /usr/share/postgresql/postgresql.conf.sample
            - source: prov_setup
              target: /docker-entrypoint-initdb.d/setup.sh
        ports:
            - 5432:5432
        networks:
            - pgnet

    subscriber:
        hostname: 'subscriber95'
        image: mypglog:9.5-raw
        #command: 'postgres -c config_file=/etc/postgresql/postgresql.conf'
        environment:
            - POSTGRES_PASSWORD=pass
            - POSTGRES_USER=primaryuser
            - POSTGRES_DB=testdb
        configs:
            - source: tables
              target: /docker-entrypoint-initdb.d/init.sql
            - source: sub_config
              target: /usr/share/postgresql/postgresql.conf.sample
            - source: sub_setup
              target: /docker-entrypoint-initdb.d/sub_setup.sh
        ports:
            - 5433:5432
        networks:
            - pgnet